config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'
  resources :songs
  resources :artists
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  mount_uploader :artistphoto, ArtistphotoUploader
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  accepts_nested_attributes_for :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def new
    @artist = Artist.new
  end

  def create
    if @artist = Artist.create(artist_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end


  private

  def artist_params
    params.require(:artist).permit(:first_name, :last_name, :birth_date, :artistphoto)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.joins(:artist).all
  end
  def show
    @song = Song.find(params[:id])
    @artist = @song.artist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_artist.html.erb
<div class="artist">
  <h3>
    <%= artist.first_name %>
    <%= artist.last_name %>
    <%= artist.birth_date %>
    <%= image_tag artist.artistphoto.thumb %>
    <%= link_to "Go to artist's page", artist, class: "btn btn-primary", role: "button" %>

  </h3>
</div>
  <h3> songs </h3>

      <% artist.songs.each do |song| %>

<div class="table">
	<div class="row">
		<div class="col-md-8 l-main">
			<h4 class="l-title"><%= song.title %></h4>
      <p>
          <%= link_to "Go to artist's page", artist, class: "btn btn-primary", role: "button" %>
      </p>
		</div>
	</div>
</div>

<% end %>

app/views/artists/index.html.erb
<h1>A collection of artists</h1>

<div>
  <%= render @artists %>
</div>

app/views/artists/new.html.erb
  <div class="artistform">
    <h4>New Artist</h4>

<%= form_for @artist do |f| %>

<div>
  <p><%= f.label :first_name %></p>
<%= f.text_field :first_name %>
</div>
<div>
  <p><%= f.label :last_name %></p>
  <%= f.text_field :last_name %>
</div>
<div>
  <p><%= f.label :birth_date %></p>
  <%= f.date_select :birth_date %>
</div>
<div>
  <p><%= f.label :artistphoto %></p>
  <%= f.file_field :artistphoto %>
</div>
<div>
  <%= f.submit "Save artist!" %>
  <% end %>
</div>
</div>

app/views/artists/show.html.erb
<div class="artist">
  <h3>
    <%= @artist.first_name %>
    <%= @artist.last_name %>
    <%= @artist.birth_date %>
    <%= image_tag @artist.artistphoto.thumb %>
  </h3>
</div>
  <h3> songs: </h3>

      <% @artist.songs.each do |song| %>

<div class="table">
	<div class="row">
		<div class="col-md-8 l-main">
			<h2><%= link_to song.title, song %></h2>
		</div>
	</div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_song.html.erb
<div class="col-sm-6 col-md-4">
  <div class="caption">
    <h3><%= song.title %></h3>
    <p><%= song.release_date %></p>
    <p> highest hot100 ranking: <%= song.highest_chart_rating %> </p>

    <article>
      <h3>Performing artist</h3>
      <p>
        <%= song.artist.first_name %> <%= song.artist.last_name %>
      </p>
    </article>
    <p>
        <%= link_to "Read more", song.artist, class: "btn btn-primary", role: "button" %>
    </p>
  </div>
</div>

app/views/songs/index.html.erb
<h1>Collection of songs</h1>

<div>
  <%= render @songs %>
</div>

app/views/songs/show.html.erb
<div class="row">
  <div class="page-header">
    <h1><%= @song.title %></h1>
  </div>

  <article class="song col-sm-8">
    <p>highest chart rating: <%= @song.highest_chart_rating %></p>
  </article>

  <aside class="col-sm-2">
    <h4> Performing artist </h4>
    <div class="table">
    	<div class="row">
    		<div class="col-md-8 l-main">
    			<h2><%= link_to "#{@song.artist.first_name} #{@song.artist.last_name} ", artist_path(@artist) %></h2>
    		</div>
    	</div>
    </div>
  </aside>
</div>